### ISSUE TITLE
Use Box Shadow to make it attractive.

### ISSUE THREAD

**Issue by dvig14** [hctnm2/hacktoberfest-2022#2]
can u assign me this issue with hacktoberfest label.

**Comment by hctnm2** [comment]
Create a PR then ill accept it on 1st October

**Comment by dvig14** [comment]
Done. n tnx😊

**Comment by dvig14** [comment]
I have create a pr now or on 1st Oct. Only.

**Comment by hctnm2** [comment]
You can make pr now apparently its open

**Comment by sakshi135** [comment]
I want to work on this. Please assign me this.

**Comment by Abhishek3223** [comment]
I want to work on this. Please assign me this.

**Comment by hctnm2** [comment]
You don't need to be assigned to a issue just create a pr and I will accept it with hacktoberfest label
